services:
  - type: web
    name: stock-backend
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: apachectl start
    envVars:
      - key: WEB_CONCURRENCY
        value: 1
      - key: DOCUMENT_ROOT
        value: public